In [9]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from gbor.main import BoostedOrdinal
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV
import time
from sklearn.model_selection import cross_val_score, RepeatedKFold

wine_red = pd.read_csv('../data/winequality-red.csv', sep = ';')
#wine_red = pd.read_csv('../data/winequality-white.csv', sep = ';')
wine_red['quality'] = wine_red['quality'] - np.min(wine_red['quality'])

wine_red_filtered = wine_red[(wine_red['quality'] != 5) & (wine_red['quality'] != 0)]

X, y = wine_red_filtered.drop(columns = ['quality']).to_numpy(), wine_red_filtered['quality'].to_numpy(dtype = 'int')

In [10]:
BoostedOrdinal._initialize_thresholds(y)

array([       -inf, -1.82851066, -0.08226415,  1.14226997])

In [11]:
BoostedOrdinal._initialize_thresholds(y, n_class = 6)

array([       -inf, -1.82851066, -0.08226415,  1.14226997,         inf])

In [12]:
BoostedOrdinal._initialize_thresholds(y, n_class = 6, laplace_smoothing = True)

array([-3.22307333, -1.81351326, -0.08195045,  1.13849368,  3.22307333])