In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from gbor.main import BoostedOrdinal
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV
import time
from sklearn.model_selection import cross_val_score, RepeatedKFold
from enum import Enum

wine_red = pd.read_csv('../data/winequality-red.csv', sep = ';')
#wine_red = pd.read_csv('../data/winequality-white.csv', sep = ';')
wine_red['quality'] = wine_red['quality'] - np.min(wine_red['quality'])

X, y = wine_red.drop(columns = ['quality']).to_numpy(), wine_red['quality'].to_numpy(dtype = 'int')

In [7]:
gbor = BoostedOrdinal(
    n_iter_no_change = 10, max_iter = 1000
    , base_learner = DecisionTreeRegressor(max_depth = 6)
    , lr_g = 5e-2
    , lr_theta = 5
    , validation_stratify = False
    , validation_fraction = 0.2
)
start_time = time.time()
gbor = gbor.fit(X, y)
end_time = time.time()
print('time: {} sec'.format(round(end_time - start_time, 1)))

time: 1.1 sec


In [8]:
gbor.path['lr_theta']#, gbor.path['lr_g']

array([5.00000000e+00, 2.44140625e-03, 2.44140625e-03, 2.44140625e-03,
       2.44140625e-03, 1.22070312e-03, 2.44140625e-03, 2.44140625e-03,
       2.44140625e-03, 1.22070312e-03, 4.88281250e-03, 2.44140625e-03,
       2.44140625e-03, 1.22070312e-03, 4.88281250e-03, 2.44140625e-03,
       2.44140625e-03, 2.44140625e-03, 2.44140625e-03, 1.22070312e-03,
       9.76562500e-03, 2.44140625e-03, 2.44140625e-03, 2.44140625e-03,
       2.44140625e-03, 2.44140625e-03, 2.44140625e-03, 2.44140625e-03,
       2.44140625e-03, 2.44140625e-03, 2.44140625e-03, 2.44140625e-03,
       2.44140625e-03, 2.44140625e-03, 2.44140625e-03, 2.44140625e-03,
       2.44140625e-03, 2.44140625e-03, 4.88281250e-03, 2.44140625e-03,
       2.44140625e-03, 2.44140625e-03, 2.44140625e-03, 2.44140625e-03,
       4.88281250e-03, 2.44140625e-03, 4.88281250e-03, 2.44140625e-03,
       2.44140625e-03, 2.44140625e-03, 4.88281250e-03, 2.44140625e-03,
       4.88281250e-03, 2.44140625e-03, 4.88281250e-03])

In [9]:
gbor.n_iter

44

In [10]:
gbor.path['loss'][::2], gbor.path['loss_holdout']

(array([1527.77217137, 1498.29031372, 1472.02005131, 1446.2684715 ,
        1422.26638457, 1399.19580721, 1376.99476397, 1357.03398127,
        1335.90459432, 1316.3219846 , 1297.20895382, 1279.50410361,
        1263.28724276, 1246.76246149, 1229.8496833 , 1214.26710289,
        1199.26990399, 1186.64610231, 1173.97695989, 1159.92629051,
        1147.14706799, 1135.6939356 , 1123.1502433 , 1111.50417122,
        1099.74496237, 1088.88890175, 1079.35727511, 1069.69909876,
        1059.64095777, 1050.28098266, 1042.19281156, 1032.9391263 ,
        1024.10891041, 1015.08939487, 1005.99840318,  998.00658344,
         989.54206583,  982.67247637,  974.74701849,  967.75572068,
         960.74413941,  953.4520846 ,  946.03168669,  939.50525081,
         932.3714238 ,  924.1900826 ,  917.40593292,  911.21622394,
         905.04514234,  899.94497306,  893.26118623,  886.53260621,
         880.34809079,  874.23410381,  868.36147661]),
 array([366.84725447, 361.85701542, 357.54688865, 353.8978141